### ISSUE TITLE
Bundler - For the installer, update `bundle_install` method to mimic Blacklight 

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight_sidecar_images#28]
Per @dl-maura

```
run  bundle install from "."
Fetching gem metadata from https://rubygems.org/..........
There was an error while trying to write to
`/usr/local/bundle/cache/bundler/git`. It is likely that you need to grant write
permissions for that path.
```

We should try adopting the `bundle_install` method that Blacklight ships with by default:
https://github.com/projectblacklight/blacklight/blob/main/lib/generators/blacklight/install_generator.rb#L43-L49

Also, `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`

**Comment by dl-maura** [comment]
So, we do need to switch to unbundled_env, which I will make a PR for, but my error is because of how my docker is setup. I am specifically overriding the clean/default bundler config to have my stuff in a different non-root user folder and when using the clean/unbundled method that gets ignored. For this to work for me, I need to use the with_original_env. There may also be a way to do the install within the Dockerfile that avoids this

**Comment by ewlarson** [comment]
Closing via #29
